version = "1.0"

[[key]]
label = "stevelr_mlinference"
roles = ["creator"]
key = "CbYMLLWCm0A+RCJLcqGA7mOCzRWrp4APrO0my2eGvN8="
labelSignature = "6zus28esUH8b9S45hiR8Hl2rGrlFqsAihp/3vurf9/9pSjk6LKrWgoeJfQdrGuHYUvvINbYIE3fYf/gIWLQ3AA=="

