# mlinference Makefile

CAPABILITY_ID = "wasmcloud:mlinference"
NAME = "mlinference"
VENDOR = "wasmCloud"
PROJECT = mlinference
VERSION = 0.2.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

